#!/bin/bash

## Description: Run npm inside the default theme directory
## Usage: theme [flags] [args]
## Example: "ddev theme install" or "ddev theme watch" or "ddev theme build"
## ExecRaw: true
## HostWorkingDir: true

if [ $1 = "watch" ] || [ $1 = "dev" ]; then
    npm --prefix themes/default run dev
elif [ $1 = "prod" ] || [ $1 = "build" ]; then
    npm --prefix themes/default run build
else
    npm --prefix themes/default "$@"
fi

